# Generated by Django 6.0 on 2025-12-12 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_group', models.CharField(choices=[('Andrea', 'Famiglia Andrea'), ('Fabrizio', 'Famiglia Fabrizio')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('NEGOTIATION', 'In Negoziazione'), ('APPROVED', 'Approvata'), ('REJECTED', 'Rifiutata'), ('CANCELLED', 'Cancellata'), ('DEROGA', 'Richiesta Revisione')], default='NEGOTIATION', max_length=20)),
                ('pending_with', models.CharField(blank=True, choices=[('Andrea', 'Famiglia Andrea'), ('Fabrizio', 'Famiglia Fabrizio')], max_length=20, null=True)),
                ('rejection_note', models.TextField(blank=True, null=True)),
                ('original_start_date', models.DateField(blank=True, null=True)),
                ('original_end_date', models.DateField(blank=True, null=True)),
                ('deroga_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deroga_requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deroga_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookingAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='bookings.booking')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_group', models.CharField(choices=[('Andrea', 'Famiglia Andrea'), ('Fabrizio', 'Famiglia Fabrizio')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
