# Generated by Django 6.0 on 2025-12-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_userprofile_callmebot_apikey_userprofile_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Immagine del profilo', null=True, upload_to='avatars/'),
        ),
    ]
